### ISSUE TITLE
splash screen blocks push notification

### ISSUE THREAD

**Issue by BDPServer** [07JP27/lottie-splash#1]
Hi,

In my app i used same splash screen . But this screen push notification . Please help me . I am not able to move ahead.

Here is my code.
1. SplashViewController 
  public partial class SplashViewController : UIViewController
    {
        public SplashViewController() : base("SplashViewController", null)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            var animationView = LOTAnimationView.AnimationNamed("loading_gears");
            var boundSize = UIScreen.MainScreen.Bounds.Size;
            animationView.Frame = new CGRect(x: 0, y: 0, width: boundSize.Width, height: boundSize.Height);
            animationView.ContentMode = UIViewContentMode.ScaleAspectFit;

            this.View.AddSubview(animationView);
            animationView.PlayWithCompletion((animationFinished) =>
            {
                UIApplication.SharedApplication.Delegate.FinishedLaunching(UIApplication.SharedApplication,
                                                                           new Foundation.NSDictionary());
            });          
            
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
        }
    }

2.  App delegate:

 [Register("AppDelegate")]
    public partial class AppDelegate : FormsApplicationDelegate
    {
       
        public override UIWindow Window { get; set; }
        //
        // This method is invoked when the application has loaded and is ready to run. In this 
        // method you should instantiate the window, load the UI into it and then make the window
        // visible.
        //
        // You have 7 seconds to return from this method, or iOS will terminate your application.
        //      
       public SplashViewController initialViewController;
        public override bool FinishedLaunching(UIApplication uiApplication, NSDictionary launchOptions)
        {
            if (Window == null)
            {
                Window = new UIWindow(frame: UIScreen.MainScreen.Bounds);
                initialViewController= new SplashViewController();
                Window.RootViewController = initialViewController;

                Window.MakeKeyAndVisible();
                return true;
            }
            else
            {
                try
            {
                    MessagingCenter.Subscribe<AuthorizationService>(this, "device_token", SetDeviceToken);
                Xamarin.Forms.Forms.Init();
                //UINavigationBar.Appearance.TintColor = Color.Red.ToUIColor();
                CachedImageRenderer.Init();
                CarouselViewRenderer.Init();
                TintedImageRenderer.Init();
                AnimationViewRenderer.Init();

                }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
            }
           
            LoadApplication(new App(new ClickNotificationModel()));
            //uiApplication.KeyWindow.TintColor = UIColor.Black;
            return base.FinishedLaunching(uiApplication, launchOptions);
            }
        }

        //application:didReceiveRemoteNotification:fetchCompletionHandler
        
        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, System.Action<UIBackgroundFetchResult> completionHandler)
        {
            UIApplication.SharedApplication.ApplicationIconBadgeNumber = 0;
            var result = Push.DidReceiveRemoteNotification(userInfo);
            System.Console.WriteLine(userInfo.ToString());
            if (result)
            {
                completionHandler?.Invoke(UIBackgroundFetchResult.NewData);
            }
            else
            {
                completionHandler?.Invoke(UIBackgroundFetchResult.NoData);
            }
        }

      

        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            Push.RegisteredForRemoteNotifications(deviceToken);
        }
        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            Push.FailedToRegisterForRemoteNotifications(error);
        }
        public override void OnActivated(UIApplication uiApplication)
        {
            base.OnActivated(uiApplication);
            UIApplication.SharedApplication.ApplicationIconBadgeNumber = 0;
        }
        public override void WillEnterForeground(UIApplication uiApplication)
        {
            base.WillEnterForeground(uiApplication);
            UIApplication.SharedApplication.ApplicationIconBadgeNumber = 0;
            //Config.ResestBadge();
        }

        public override void ReceivedRemoteNotification(UIApplication application, NSDictionary userInfo)
        {
            UIApplication.SharedApplication.ApplicationIconBadgeNumber = 0;
            base.ReceivedRemoteNotification(application, userInfo);
        }

    }

**Comment by 07JP27** [comment]
I can read your intent is below.
- Want receive push notification in this app.
- But now, you can't launch app or can't receive push notification.

Are those correct?

Please tell me more detail of your intent(thing you want to develop), current happened problem(behavior) and your develop environment.

**Comment by BDPServer** [comment]
Hi. 

app launched successfully. Also i am getting push notification. But application is not redirecting to details page. Every time application start from splash screen and goes to home page.

**Comment by 07JP27** [comment]
OK, I understood.

Refer this project. → https://github.com/07JP27/17nsj-app-for-mobile

This project implemented Lottie splash screen and receive push notification.
And processing correctly.

In this project, using Microsoft App Center push notification(https://docs.microsoft.com/en-us/appcenter/push/) .
And the invoked method when receive push notification is written in  App.xaml.cs. (https://github.com/07JP27/17nsj-app-for-mobile/blob/master/_17NSJ.Shared/App.xaml.cs)
Nothing related push notification method  in AppDelegate.

Check different between my project and your project.

**Comment by BDPServer** [comment]
Thanks for your support . I will check and will get back to you

**Comment by BDPServer** [comment]
Thank you so much . It works on ios . But in Andriod, After splash I am getting black screen for 5-10 sec.

**Comment by 07JP27** [comment]
Check start timing of OnAnimationEnd method using break point in your VisualStudio.
When is the OnAnimationEnd method called?
Started black screen? or end of that?

OnAnimationEnd is here(https://github.com/07JP27/17nsj-app-for-mobile/blob/master/_17NSJ.Droid/SplashActivity.cs).

**Comment by BDPServer** [comment]
I used the same .
 public void OnAnimationEnd(Animator animation)
        {
            StartActivity(new Intent(Application.Context, typeof(MainActivity)));
            //StartActivity(typeof(MainActivity));
        }
But still i am getting black screen

**Comment by BDPServer** [comment]
It started with back screen . After back screen MainPage launched

**Comment by 07JP27** [comment]
If remove your lottie splash screen, no display black screen?
Or black screen for 5-10 sec still continue?

**Comment by BDPServer** [comment]
Yes . If I  removed lottie that time no black screen is there.

Thanks
Regards
Dharm

**Comment by 07JP27** [comment]
This phenomenon not seem related for lottie splash screen.
Because this phenomenon keep happen after remove lottie.
So I recommend ask to more many developer using Xamarin Forum about this phenomenon.

**Comment by 07JP27** [comment]
Do you have any questions?
If you don't have, I will close this issue.

**Comment by BDPServer** [comment]
Thank you so much. Black screen issue is solved. But still in push
notifications case , page is not redirecting to detail page.

Thanks & Regards
Dharm

**Comment by 07JP27** [comment]
Which OS? iOS, android or both?

**Comment by BDPServer** [comment]
Both

**Comment by 07JP27** [comment]
Sorry, I can not reappearance your problem in my environment :(

**Comment by BDPServer** [comment]
Hi,
Can you share me lottie splash screen with push  notification project. If
there is any project on git

**Comment by 07JP27** [comment]
lottie splash screen with push  notification project is here
https://github.com/07JP27/lottie-splash/issues/1#issuecomment-454712794

**Comment by BDPServer** [comment]
I already check . In project we are showing alert on main page if push
notification  received. But my requirement is when I received that time app
should be in detail page.

**Comment by 07JP27** [comment]
Confirm.
Is your required behavior is transition to detail page due to data in push notification?

**Comment by BDPServer** [comment]
Actually what happend  first when notification  got it goes to push
notification received method than it comes to splash screen after animation
and it goes to app.cs class and than goes to home page.

**Comment by 07JP27** [comment]
Sorry, I can not understanding your requirement & current problems. Could you take the screenshot ,video or any graphically way?
