### ISSUE TITLE
Error - AddAnimatorListener 

### ISSUE THREAD

**Issue by lucagto** [07JP27/lottie-splash#2]
Hi,
I followed your guide and I have a problem, in the file SplashActivity.cs, 

```
var animationView = FindViewById(Resource.Id.animation_view);
            animationView.AddAnimatorListener(this);
```

> Error CS1061 'View' does not contain a definition for 'AddAnimatorListener' and no accessible extension method 'AddAnimatorListener' was found that accepts a first argument of type 'View'. Probably missing a using directive or an assembly reference

Thank you.

**Comment by 07JP27** [comment]
Resolved?
